replace tabs with spaces for indent
Change-Id: Ia545b096ed318b7f304b39c973b4b04dfe2ab6cb

diff --git a/handlers/mariabackup_full.in b/handlers/mariabackup_full.in
--- a/handlers/mariabackup_full.in
+++ b/handlers/mariabackup_full.in
@@ -33,7 +33,7 @@ fi
 # check if mysqld is alive
 mysqladmin ping 1>/dev/null
 if [ $? -ne 0 ]; then
-	echo "ERROR: mysqld seems to be dead..."
+   echo "ERROR: mysqld seems to be dead..."
 fi
 
 # test the connection to the server
@@ -64,6 +64,6 @@ echo "Starting full backup of databases to ${directory}"
 eval $exec
 
 if [ $? -ne 0 ]; then
-	exit_code=$?
-	echo "FAILURE: something went wrong... exiting with ${exit_code}"
+   exit_code=$?
+   echo "FAILURE: something went wrong... exiting with ${exit_code}"
 fi
