make a structure dump of db's in mariabackup.handler
To make a partial restore of a database possible with mariabackup a structure dump is needed to create the necessary structure of the database before importing the files back to the data-dir of mariadb.

Change-Id: I7ec4250daaacd1b94dff81ceb02b7e0b587f90ca

diff --git a/handlers/mariabackup_full.in b/handlers/mariabackup_full.in
--- a/handlers/mariabackup_full.in
+++ b/handlers/mariabackup_full.in
@@ -2,7 +2,6 @@
 # TODO: execute only if all tests are passed
 
 set -e
-
 setsection databases
 getconf db_includes
 getconf db_excludes
@@ -67,3 +66,54 @@ if [ $? -ne 0 ]; then
    exit_code=$?
    echo "FAILURE: something went wrong... exiting with ${exit_code}"
 fi
+
+# check for a full backup
+if [ -z "$db_includes" -a -z "$db_excludes" ]; then
+   exit 0
+fi
+
+## preparation for a restore ##
+
+# to make a partial restore possible without creating all databases and tables manually
+# a mysqldump of the structure is made
+
+# make a directory for the structure dumps of the databases included in the backup
+mkdir "${directory}/structure-dumps/"
+
+# get a list of all databases and remove "Database"
+databases=$(echo "SHOW DATABASES;" | mysql)
+databases="${databases#'Database'}"
+
+# strip the first and last quotes from includes & excludes
+db_includes=${db_includes#\"}
+db_includes=${db_includes%\"}
+db_excludes=${db_excludes#\"}
+db_excludes=${db_excludes%\"}
+
+
+# iterate over the list of databases for excludes set
+for database in $databases; do
+
+   if [ ! -z "$db_excludes" ]; then
+      # skip the databases that are part of the excludes
+      if [[ " $db_excludes " =~  .*\ $database\ .* ]];then
+         echo "Skipping excluded ${database}"
+         continue
+      fi
+    fi
+
+   if [ ! -z "$db_includes" ]; then
+       if [[ ! " $db_includes " =~  .*\ $database\ .* ]];then
+          echo "Skipping not included $database"
+          continue
+       fi
+   fi
+
+   # make a structure dump per databases so the restore of a single database
+   # out of a full backup is possible
+   target_file=${directory}/structure-dumps/${database}.sql
+   echo "Making structure dump of ${database}"
+   mysqldump --no-data $database > $target_file || echo "ERROR: failed to make a structure dump of ${database}"
+   echo "SUCCESS: making a structure dump of ${database}"
+done
+
